[package]
name = "sylo"
version = "0.1.0"
authors = ["Sam C <sc14809@my.bristol.ac.uk>"]
edition = "2018"
publish = false

#[build-dependencies]
# cc = "1.0.69"
# bindgen = "0.58.1"

[profile.release]
debug = 1