[package]
name = "sylo"
version = "0.1.0"
authors = ["Sam C <sc14809@my.bristol.ac.uk>"]
edition = "2018"
publish = false

[dependencies]
regex-deriv = { path = "../rust-regex-deriv" }
lr-parsing-tools = { path = "../rust-lr-parsing-tools" }

[profile.release]
debug = 1